# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pressure', models.CharField(max_length=2)),
                ('pressure_flag', models.CharField(max_length=1)),
                ('vibrance', models.CharField(max_length=5)),
                ('vibrance_flag', models.CharField(max_length=1)),
                ('temperature', models.CharField(max_length=4)),
                ('temperature_flag', models.CharField(max_length=1)),
                ('time', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'db_table': 'zigbee',
            },
        ),
    ]
